name: null
project: Lux_AI_2021
entity: isaiahpressman
group: attention
act_space: BasicActionSpace
obs_space: FixedShapeEmbeddingObs
obs_space_kwargs:
  include_subtask_encoding: false
reward_space: PunishingExponentialReward
reward_space_kwargs: {}
total_steps: 100000000.0
num_actors: 2
n_actor_envs: 16
unroll_length: 16
batch_size: 4
discounting: 0.99
model_arch: attention_model
n_blocks: 4
hidden_dim: 128
normalize: true
use_index_select: true
mhsa_heads: 2
optimizer_class: Adam
optimizer_kwargs:
  lr: 0.0001
  eps: 0.0003125
min_lr_mod: 0.01
entropy_cost: 0.001
baseline_cost: 1.0
lmb: 0.8
reduction: sum
actor_device: cuda:1
learner_device: cuda:0
disable_wandb: false
model_log_freq: 100
sharing_strategy: file_descriptor
seed: null
num_buffers: 4
use_mixed_precision: true
clip_grads: 10.0
checkpoint_freq: 10.0
num_learner_threads: 1
load_dir: null
debug: false
