name: null
project: Lux_AI_2021
entity: isaiahpressman
group: conv
act_space: BasicActionSpace
obs_space: FIXED_SHAPE_CONTINUOUS_OBS
reward_space: CityTileReward
total_steps: 100000000.0
num_actors: 2
n_actor_envs: 16
unroll_length: 5
batch_size: 16
discounting: 0.9995
model_arch: conv_model
n_blocks: 8
hidden_dim: 128
normalize: true
use_index_select: true
kernel_size: 5
mhsa_heads: 4
optimizer_class: RMSprop
optimizer_kwargs:
  lr: 0.0001
  alpha: 0.9
min_lr_mod: 0.01
entropy_cost: 0.0002
baseline_cost: 1.0
actor_device: cuda:1
learner_device: cuda:0
disable_wandb: false
model_log_freq: 100
sharing_strategy: file_descriptor
seed: 42
num_buffers: 4
use_mixed_precision: true
reduction: mean
clip_grads: 10.0
checkpoint_freq: 20.0
num_learner_threads: 1
load_dir: null
