name: null
project: Lux_AI_2021
entity: isaiahpressman
group: conv
act_space: BasicActionSpace
obs_space: FixedShapeContinuousObs
obs_space_kwargs:
  include_subtask_encoding: false
reward_space: StatefulMultiReward
reward_space_kwargs:
  step: 0.005
total_steps: 100000000.0
num_actors: 2
n_actor_envs: 16
unroll_length: 16
batch_size: 4
discounting: 0.999
model_arch: conv_model
n_blocks: 4
hidden_dim: 128
normalize: false
use_index_select: true
kernel_size: 5
optimizer_class: Adam
optimizer_kwargs:
  lr: 0.0002
  eps: 0.0003
min_lr_mod: 0.01
entropy_cost: 0.001
baseline_cost: 2.0
lmb: 0.8
reduction: sum
actor_device: cuda:1
learner_device: cuda:0
disable_wandb: false
model_log_freq: 100
sharing_strategy: file_descriptor
seed: null
num_buffers: 4
use_mixed_precision: true
clip_grads: 10.0
checkpoint_freq: 10.0
num_learner_threads: 1
load_dir: null
debug: false
