device: player_id
#device: cpu

# Use manual preference based collision detection
use_collision_detection: True
# Bans no-ops after the first night until research is complete
# Has no effect when use_collision_detection is False
must_research: False