import getpass

from .lux.constants import Constants
from .lux.game_constants import GAME_CONSTANTS

USER = getpass.getuser()
LOCAL_EVAL = USER in ['isaiah']

# Shorthand constants
DAY_LEN = GAME_CONSTANTS["PARAMETERS"]["DAY_LENGTH"]
CYCLE_LENGTH = GAME_CONSTANTS["PARAMETERS"]["NIGHT_LENGTH"]
COLLECTION_RATES = GAME_CONSTANTS["PARAMETERS"]["WORKER_COLLECTION_RATE"]

# Derived constants
MAX_FACTORIES = 2
MAX_RESOURCE = {
    Constants.RESOURCE_TYPES.WOOD: GAME_CONSTANTS["PARAMETERS"]["MAX_WOOD_AMOUNT"],
    Constants.RESOURCE_TYPES.COAL: 425.,
    Constants.RESOURCE_TYPES.URANIUM: 350.
}
MAP_SIZE = (48, 48)
