defaults:
- override hydra/job_logging: colorlog
- override hydra/hydra_logging: colorlog

name: null

## WANDB params
# The wandb project name
project: Lux_AI_2021
# The wandb user to log to
entity: isaiahpressman
# The wandb group for the run
group: conv

## ENV params
act_space: BasicActionSpace
obs_space: FixedShapeContinuousObs
obs_space_kwargs:
  include_subtask_encoding: False
reward_space: StatefulMultiReward
reward_space_kwargs:
  #early_stop: True
  negative_weight: 1.01
  #research: 0.01
  #fuel: 0.
  game_result: 50.
  step: 0.1

## TRAINING params
total_steps: 1e8
num_actors: 2
n_actor_envs: 16
unroll_length: 16
batch_size: 4
discounting: 0.999

## MODEL params
model_arch: conv_model
n_blocks: 8
hidden_dim: 128
normalize: False
use_index_select: True
# Conv-specific params
kernel_size: 5


## OPTIMIZER params
optimizer_class: Adam
optimizer_kwargs:
  lr: 2e-4
  # See https://arxiv.org/pdf/2105.05246.pdf
  eps: 0.0003
  #alpha: 0.9
min_lr_mod: 0.01

## LOSS params
entropy_cost: 0.001
baseline_cost: 2.
# lambda parameter for TD-lambda and UPGO losses
lmb: 0.8
reduction: sum

# MISCELLANEOUS params
actor_device: cuda:1
learner_device: cuda:0
disable_wandb: False
model_log_freq: 100
# file_descriptor or file_system
sharing_strategy: file_descriptor

# Continue from previous run
#load_dir: /Windows/Users/isaia/Documents/GitHub/Kaggle/Lux_AI_2021/outputs/2021-08-10/11-28-49/
#checkpoint_file: 001653120.pt
