defaults:
- override hydra/job_logging: colorlog
- override hydra/hydra_logging: colorlog

hydra:
  run:
    dir: ./outputs/${now:%m-%d}/${now:%H-%M-%S}

# Parameters to overwrite
lmb: 0.85

# Continue from previous run
load_dir: /Windows/Users/isaia/Documents/GitHub/Kaggle/Lux_AI_2021/outputs/10-01/15-27-32/
checkpoint_file: 10756544.pt
weights_only: False

# Convenience for debugging
#disable_wandb: False
#debug: False