defaults:
- override hydra/job_logging: colorlog
- override hydra/hydra_logging: colorlog

hydra:
  run:
    dir: ./outputs/${now:%m-%d}/${now:%H-%M-%S}

# Parameters to overwrite
#total_steps: 4e7
#teacher_load_dir: /Windows/Users/isaia/Documents/GitHub/Kaggle/Lux_AI_2021/outputs/10-20/03-00-03/
#teacher_checkpoint_file: 06207104.pt

# Continue from previous run
load_dir: /Windows/Users/isaia/Documents/GitHub/Kaggle/Lux_AI_2021/outputs/10-26/00-48-43/
checkpoint_file: 02281792.pt
weights_only: False

# Convenience for debugging
#disable_wandb: False
#debug: False