defaults:
- override hydra/job_logging: colorlog
- override hydra/hydra_logging: colorlog

hydra:
  run:
    dir: ./outputs/${now:%m-%d}/${now:%H-%M-%S}

# Parameters to overwrite
#total_steps: 6e7
#teacher_load_dir: /Windows/Users/isaia/Documents/GitHub/Kaggle/Lux_AI_2021/outputs/11-01/00-18-25/
#teacher_checkpoint_file: 30555200.pt

# Continue from previous run
load_dir: /Windows/Users/isaia/Documents/GitHub/Kaggle/Lux_AI_2021/outputs/11-11/18-56-29/
checkpoint_file: 05875584.pt
weights_only: False

# Convenience for debugging
#disable_wandb: False
#debug: False